In [1]:
import numpy as np
import pandas as pd
import string
import re
import random
import pickle
import os

with open(r'D:\smarterdevOCRScanner\1_WorkOrderNER\TSV FILES\workOrders.txt', mode='r', encoding='utf8', errors='ignore') as f:
    text = f.read()

data = list(map(lambda x:x.split('\t'),text.split('\n')))

df = pd.DataFrame(data[1:],columns=data[0])

df.head(10)

                     id    text tag
0  Alandemel_page_1.png           O
1  Alandemel_page_1.png  /‘Nian   O
2  Alandemel_page_1.png      de   O
3  Alandemel_page_1.png    Maic   O
4  Alandemel_page_1.png           O
5  Alandemel_page_1.png   WORKS   O
6  Alandemel_page_1.png   ORDER   O
7  Alandemel_page_1.png     TO:   O
8  Alandemel_page_1.png       |   O
9  Alandemel_page_1.png     D&S   O

In [2]:
### Cleaning Text - Remove white space - Remove Unwanted special characters
whitespace = string.whitespace
punctuation = "!#$%&\'()*+:;<=>?[\\]^`{|}~"
tableWhitespace = str.maketrans('','',whitespace)
tablePunctuation = str.maketrans('','',punctuation)
def cleanText(txt):
    text = str(txt)
    text = text.lower()
    removewhitespace = text.translate(tableWhitespace)
    removepunctuation = removewhitespace.translate(tablePunctuation)
    
    return str(removepunctuation)

df['text'] = df['text'].apply(cleanText)
dataClean = df.query("text != '' ")
dataClean.dropna(inplace=True)
dataClean.head(10)

C:\Users\USER\AppData\Local\Temp\ipykernel_30044\2534761583.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataClean.dropna(inplace=True)

                      id        text tag
1   Alandemel_page_1.png      /‘nian   O
2   Alandemel_page_1.png          de   O
3   Alandemel_page_1.png        maic   O
5   Alandemel_page_1.png       works   O
6   Alandemel_page_1.png       order   O
7   Alandemel_page_1.png          to   O
9   Alandemel_page_1.png          ds   O
10  Alandemel_page_1.png  appliances   O
12  Alandemel_page_1.png          mr   O
13  Alandemel_page_1.png   stedeford   O

In [3]:
### Convert Data into Spacy Format

group = dataClean.groupby(by='id')
workorders = group.groups.keys()
allWorkOrdersData = []
for workorder in workorders:
    workOrderData = []
    grouparray = group.get_group(workorder)[['text','tag']].values
    content = ''
    annotations = {'entities':[]}
    start = 0
    end = 0
    for text, label in grouparray:
        text = str(text)
        stringLength = len(text) + 1

        start = end
        end = start + stringLength

        if label != 'O':
            annot = (start,end-1,label)
            annotations['entities'].append(annot)

        content = content + text + ' '
        
        
    workOrderData = (content,annotations)
    allWorkOrdersData.append(workOrderData)


allWorkOrdersData

[('/‘nian de maic works order to ds appliances mr stedeford 136-137 high street ilfracombe ex34 9ez please execute the other- appliance at 571493 flat e 7 oaklands road _ bromley br1 3sj contact tel contact mr frederick william gregory -7539216864 cat 2 - hotpoint / indesit - £499 vat manufacturers warranty - 1 year "delivery," "installation," and removal - £99 vat date 15/11/2023 order bros-11206742 ordered by jeri davison bromley pmc con.fax access tenant key return keys property 571493 stoptap please contact the office below with a quotation prior to carrying out any works. required by 24/11/23 000 as this works order has been placed on behalf of the "landlord," your invoice must be addressed directly to the landlord miss androniki chlorou c/o bromley adm and alan de maid bromley 19 east "street," bromley kent br1 1qe _ please emaul 7 send all unvouces to tre office address below office address 19 east "street," "bromley," "kent," bri 1qe phone 208 466 7172 fax 208 4666331 e-mail lettings@alandemaid.co.uk ',
  {'entities': [(97, 103, 'B-FAULTDETAIL'),
    (104, 111, 'I-FAULTDETAIL'),
    (112, 115, 'I-FAULTDETAIL'),
    (116, 122, 'I-FAULTDETAIL'),
    (123, 132, 'I-FAULTDETAIL'),
    (143, 147, 'B-SHIPPINGSTREET'),
    (148, 149, 'I-SHIPPINGSTREET'),
    (150, 151, 'I-SHIPPINGSTREET'),
    (152, 160, 'I-SHIPPINGSTREET'),
    (161, 165, 'I-SHIPPINGSTREET'),
    (168, 175, 'B-SHIPPINGCITY'),
    (176, 179, 'I-SHIPPINGCITY'),
    (180, 183, 'I-SHIPPINGCITY'),
    (204, 206, 'B-SHIPPINGNAME'),
    (207, 216, 'I-SHIPPINGNAME'),
    (217, 224, 'I-SHIPPINGNAME'),
    (225, 232, 'I-SHIPPINGNAME'),
    (233, 244, 'B-SHIPPINGPHONE'),
    (245, 248, 'B-INSTRUCTIONNOTES'),
    (249, 250, 'I-INSTRUCTIONNOTES'),
    (251, 252, 'I-INSTRUCTIONNOTES'),
    (253, 261, 'I-INSTRUCTIONNOTES'),
    (262, 263, 'I-INSTRUCTIONNOTES'),
    (264, 271, 'I-INSTRUCTIONNOTES'),
    (272, 273, 'I-INSTRUCTIONNOTES'),
    (274, 278, 'I-INSTRUCTIONNOTES'),
    (279, 282, 'I-INSTRUCTIONNOTES'),
    (283, 296, 'I-INSTRUCTIONNOTES'),
    (297, 305, 'I-INSTRUCTIONNOTES'),
    (306, 307, 'I-INSTRUCTIONNOTES'),
    (308, 309, 'I-INSTRUCTIONNOTES'),
    (310, 314, 'I-INSTRUCTIONNOTES'),
    (315, 326, 'I-INSTRUCTIONNOTES'),
    (327, 342, 'I-INSTRUCTIONNOTES'),
    (343, 346, 'I-INSTRUCTIONNOTES'),
    (347, 354, 'I-INSTRUCTIONNOTES'),
    (355, 356, 'I-INSTRUCTIONNOTES'),
    (357, 360, 'I-INSTRUCTIONNOTES'),
    (361, 364, 'I-INSTRUCTIONNOTES'),
    (370, 380, 'B-ORDERDATE'),
    (387, 400, 'B-PAYMENTPONUMBER'),
    (412, 416, 'B-PAYMENTBYERNAME'),
    (417, 424, 'I-PAYMENTBYERNAME'),
    (425, 432, 'I-PAYMENTBYERNAME'),
    (433, 436, 'I-PAYMENTBYERNAME'),
    (452, 458, 'B-ACCESSKEY'),
    (593, 601, 'B-REQUIREDDATE'),
    (727, 731, 'B-PAYMENTBILLINGNAME'),
    (732, 741, 'I-PAYMENTBILLINGNAME'),
    (742, 749, 'I-PAYMENTBILLINGNAME'),
    (754, 761, 'B-PAYMENTCOMPANYNAME'),
    (762, 765, 'I-PAYMENTCOMPANYNAME'),
    (766, 769, 'I-PAYMENTCOMPANYNAME'),
    (770, 774, 'I-PAYMENTCOMPANYNAME'),
    (775, 777, 'I-PAYMENTCOMPANYNAME'),
    (778, 782, 'I-PAYMENTCOMPANYNAME'),
    (783, 790, 'I-PAYMENTCOMPANYNAME'),
    (791, 793, 'B-PAYMENTBYERADDRESS'),
    (794, 798, 'I-PAYMENTBYERADDRESS'),
    (799, 808, 'I-PAYMENTBYERADDRESS'),
    (809, 816, 'I-PAYMENTBYERADDRESS'),
    (817, 821, 'I-PAYMENTBYERADDRESS'),
    (822, 825, 'I-PAYMENTBYERADDRESS'),
    (826, 829, 'I-PAYMENTBYERADDRESS'),
    (953, 958, 'B-PAYMENTBYERPHONE'),
    (959, 962, 'I-PAYMENTBYERPHONE'),
    (963, 966, 'I-PAYMENTBYERPHONE'),
    (967, 971, 'I-PAYMENTBYERPHONE'),
    (972, 975, 'B-PAYMENTBYERFAX'),
    (976, 979, 'I-PAYMENTBYERFAX'),
    (980, 987, 'I-PAYMENTBYERFAX'),
    (995, 1020, 'B-PAYMENTBYEREMAIL')]})]

In [4]:
## Split the Data into Training and Testing Set
# Assuming allWorkOrdersData is already loaded
random.shuffle(allWorkOrdersData)

# Split the data into training and testing sets
TrainData = allWorkOrdersData[:240]
TestData = allWorkOrdersData[240:]

# Ensure the 'data' directory exists
os.makedirs('./data', exist_ok=True)

# Save the training and testing data as pickle files
with open('./data/TrainData.pickle', mode='wb') as f_train:
    pickle.dump(TrainData, f_train)

with open('./data/TestData.pickle', mode='wb') as f_test:
    pickle.dump(TestData, f_test)